### ISSUE TITLE
Add MIT/Apache License

### ISSUE THREAD

**Issue by audip** [kshehadeh/jekyll-s3-action#4]
Howdy Karim,

Hope you're doing well!

As an open-source project, can this project have a proper license (MIT or Apache) that allows the use and redistribution of this github action?

Best regards,
Aditya

**Comment by kshehadeh** [comment]
Thanks Aditya!  [Done](https://github.com/kshehadeh/jekyll-s3-action/blob/master/LICENSE.md)

**Comment by audip** [comment]
Thank you, Karim!
